name: Deploy Reactfolio to GitHub Pages
on:
  push:
    branches:
      - docker-deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reactfolio:latest

      - name: Deploy to GitHub Pages
        run: |
          docker run --rm -v $(pwd)/dist:/dist ${{ secrets.DOCKER_USERNAME }}/reactfolio:latest
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          cp -r dist/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages